from rest_framework import serializers
from api.models.location import Location
from api.models.route import Route
from api.models.trip import Trip
from api.serializers.location_serializer import LocationSerializer
from api.serializers.route_serializer import RouteSerializer

class TripSerializer(serializers.Serializer):
    # Required data
    origin = LocationSerializer()
    waypoints = LocationSerializer(many=True)

    # Not required data (will be generated by the model)
    routes = RouteSerializer(many=True, required=False)
    routes_geojson = serializers.DictField(required=False)

    def create(self, validated_data):
        origin_data = validated_data.pop('origin')
        waypoints_data = validated_data.pop('waypoints')

        origin = Location(**origin_data) # unpacks a dictionary and assigns its values to the corresponding parameters
        waypoints = [Location(**waypoint_data) for waypoint_data in waypoints_data]

        return Trip(origin=origin, waypoints=waypoints)